### ISSUE TITLE
How does file size of g.ene apps compare to file size of electron apps

### ISSUE THREAD

**Issue by erusev** [Mte90/g.ene#2]
We've been using Electron to develop http://caret.io but we are concerned with the ever increasing file size of Chromium / Electron. The simplest app would be ~ 80MB (decompressed) which we find ridiculous.

Do you think that a Gecko based approach like yours could offer smaller file sizes?

Thanks.

**Comment by Mte90** [comment]
Is a good question and i think that the best place is on https://discourse.mozilla-community.org/t/g-ene-one-day-experiment-gecko-alternative-to-electron-nw-js/7106 because i am not a Gecko developer/contributor.
Maybe something with servo is the best solution that is very light respect a gecko.

**Comment by erusev** [comment]
Thanks.
